gui:
  theme:
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red

  showFileTree: true
  showListFooter: true
  showRandomTip: true
  showBottomLine: true
  showCommandLog: true
  showIcons: true

disableStartupPopups: false
notARepository: 'skip'
os:
  editCommand: 'nvim'
